#!/bin/bash

# change to hooks dir
cd $(dirname $0)

# include GitPushy common functions
source gitpushy-common

# change to repo dir
gitpushy-cd-root

# start GitPushy on supplied branch with cron trigger
gitpushy-push-branch "$1" cron
