#!/bin/bash

# Triggers to pull from a remote repository

# config file
# $PULLY_REPO $PULLY_REMOTE $PULLY_REMOTE_URL $PULLY_BRANCH

gitpully_init() {
    while read PULLY_REPO PULLY_REMOTE PULLY_REMOTE_URL PULLY_BRANCH; do
      gitpully_line $PULLY_REPO $PULLY_REMOTE $PULLY_REMOTE_URL $PULLY_BRANCH
    done
}

gitpully_line() {
    cd $PULLY_REPO

    PULLY_REMOTE_HEAD="$(git ls-remote $PULLY_REMOTE -h $PULLY_BRANCH)"
    PULLY_LOCAL_HEAD="$(git ls-remote $PULLY_REMOTE -h $PULLY_BRANCH)"
}

