#!/bin/bash

# store STDIN for multiple use later
STDIN=$(cat -)

# include GitPushy common functions
source hooks/gitpushy-common

# initialize GitPushy
echo "$STDIN" | gitpushy-init

# You can call more post-receive hooks the same way
#
#   echo "$STDIN" | your-post-receive
#
